### ISSUE TITLE
switch statement not auto-indented correctly

### ISSUE THREAD

**Issue by ZevEisenberg** [textmate/php.tmbundle#19]
When you declare a `switch` statement with `switch[tab]`, the template looks like this:

``` php
switch (variable) {
    case 'value':
        # code...
        break;

    default:
        # code...
        break;
}
```

The code below the `case` and `default` is indented. However, when I try to add a new case by pressing `return` at the end of the first `break;`, everything stays indented one more to the right than the first case:

``` php
switch (variable) {
    case 'value':
        echo 'hello';
        break;
        case 2:
        echo 'hello';
        break;

    default:
        echo 'hello';
        break;
}
```

When I use `Command`-`Option`-`[` to Indent Line / Section, most of the statement gets flattened and doesn't match the template:

``` php
switch (variable) {
    case 'value':
    echo 'hello';
    break;
    case 2:
    echo 'hello';
    break;

    default:
    echo 'hello';
    break;
}
```

I would like the auto-indent to make it look like this:

``` php
switch (variable) {
    case 'value':
        echo 'hello';
        break;
    case 2:
        echo 'hello';
        break;

    default:
        echo 'hello';
        break;
}
```

**Comment by aaronbauman** [comment]
This problem persists to TextMate 2
Maybe there's a way to solve it now?
Is there a current issue open about this?

**Comment by infininight** [comment]
@aaronbauman No there haven't been any additions to TextMate to allow this to work.

**Comment by claylo** [comment]
I'm curious why very similar (it seems) indenting works just fine in yaml.tmbundle, but can't work on brace-less case statements. I currently get glassy-eyed quickly looking through the tmPreferences plists, but as I've been switching between editing YAML files and writing PHP switch statements on some values within those YAML files ... it just jumped out at me that they seemed pretty similar.

I'm obviously missing something, but thought I'd mention this in case those of you who are more familiar with the way indentation preferences work in TM2 might get an idea from this. Hope-hope. :pray:

**Comment by infininight** [comment]
YAML is a very different language, indentation based. We disable indentation corrections for the entire language for that reason. For PHP we want corrections and they work well in most all cases, this is the one case where they get in the way.

**Comment by claylo** [comment]
Thanks for that explanation, @infininight. I knew it had to be something like that. And I take it that we're not able to disable indentation corrections inside of a `case`?

**Comment by theosib** [comment]
I'd like to reopen this bug on account of the fact that it's been 4 years since it was reported, and my suggestion is that it can be fixed by having an option to disable auto-corrected indenting.  Or we can share mods to the auto-correction for people who want to change it.

**Comment by theosib** [comment]
I'm told that the original submitter's example is how indent is set up for Swift.  Apparently any reasons for not doing this correctly before are no longer true.  So can we get C's switch statement indentation to behave the same as Swift?

**Comment by sorbits** [comment]
Swift decreases indent for the case labels, so this is how OP’s example will indent using Swift’s rules:

	switch (variable) {
	case 'value':
		# code...
		break;

	default:
		# code...
		break;
	}

We do this for Swift because it seems to be Apple’s recommended style, and in Swift braces are never used with switch/case-statements. In PHP, were we to adopt the above style, it would be an issue when using braces with the switch/case-statements.

**Comment by theosib** [comment]
Well, my problem is that TextMate keeps fighting against having any kind of sensible indenting style in C/C++.  I'm not sure how you want to handle PHP, but it's really broken for C languages.  I would LOVE it if the C/C++ rules were to behave like Swift.  I don't care if it indents case and the code further or keeps case aligned with switch.  Either one would be joyous to me.

**Comment by sorbits** [comment]
How TextMate indents your code is based on settings.

For C/C++ you can reach the settings via the bundle editor, select C → 
Settings → Indentation Rules.

I created these rules to match my style, so while you might consider 
them broken, you will have to define exactly what your problem is, 
though you’re currently commenting on a closed issue belonging to the 
PHP bundle (i.e. it has nothing to do with C/C++).

If you are unable to setup TextMate to indent as you want, the mailing 
list or IRC channel is a better place to ask for help.
