### ISSUE TITLE
Syntax highlighting for namespace declaration on same line as opening <?php tag

### ISSUE THREAD

**Issue by martinbean** [textmate/php.tmbundle#51]
Laravel’s coding style guide says the `namespace` declaration must be on the same line as the opening `<?php` tag: http://laravel.com/docs/master/contributions#coding-style

When I do this in TextMate, the PHP syntax highlighter doesn’t pick up the namespace declaration, but does if it’s on a new line. Is it possible to add syntax highlighting if it’s on the same line as the opening `<?php` tag as well? I’d do it myself but really not _au fait_ with TextMate package development.

**Comment by infininight** [comment]
Fixed, thanks for the report.

**Comment by martinbean** [comment]
@infininight Awesome. Thanks!
