### ISSUE TITLE
New syntax and keywords for PHP 5.6

### ISSUE THREAD

**Issue by perajovic** [textmate/php.tmbundle#52]
Regarding to PHP 5.6 changelog, there are some new functions, constructs, keywords and syntax as well. All of them should be formatted, highlighted and treated as any other of these in older PHP versions.

Link to all changes can be found at http://php.net/manual/en/migration56.php.

**Comment by infininight** [comment]
Several changes have been made in this vein in commits 2150cead4697668ce7adb604a9a19c4d624c43ec...1ae104d86b303a7cf8460a4abca2125331b7bab6, if you find anything I missed please open a new issue.
