### ISSUE TITLE
Snippets File name invalid for NTFS

### ISSUE THREAD

**Issue by ArTiSTiX** [textmate/php.tmbundle#55]
I tried to clone this repo on Windows, and Some files have incorrect filenames.
Is it possible to rename some with only ASCII characters, or it is absolutely necessary to have unicode characters ?

**Comment by infininight** [comment]
Do you happen to know which files are an issue here? I found a list of `/ ? < > \ : * | "` characters but we use `<>` in a few places not sure if it's an issue or just `:`.

**Comment by ArTiSTiX** [comment]
I have issues with all files containing the symbols you listed (particularly ```< > : ?```).
Filenames containing ```:``` are stripped before the symbol, giving no extension.

**Comment by infininight** [comment]
Since this isn't an issue on Macs or with TextMate and TextMate will still generate invalid filenames I'm going to close this issue without a fix. However I would accept a pull request if someone wants to correct the filenames and test a fix.
