### ISSUE TITLE
Proper escaping in regex

### ISSUE THREAD

**Issue by MorrisJobke** [textmate/php.tmbundle#56]
Example:
```PHP
$dn = preg_replace('/([^\\\]),(\s+)/u', '\1,', $dn);
$test = 'abc';
```

In PHP `\\` is an escaped `\` and `\]` will just be ignore -> so it results in following regex: `[^\\]` (which is as regex: everything except a backslash (in regex the backslash also needs to be escaped).

Anyway. If even the regex is wrong it doesn't should cause the highlighter to break anything. The string is still closed and there the highlight should start working again.

Spotted in https://github.com/owncloud/core/blob/4fcfedb03cb60fe60617fd8d7609d5d1397789a5/apps/user_ldap/lib/access.php#L241

**Comment by infininight** [comment]
Corrected in 2150cead4697668ce7adb604a9a19c4d624c43ec, thanks for the report!
