### ISSUE TITLE
inconsistency when using doc⇥ before static properties 

### ISSUE THREAD

**Issue by koenpunt** [textmate/php.tmbundle#60]
With `protected static` the `doc⇥` handler doesn't see as a variable:

![image](https://cloud.githubusercontent.com/assets/351038/6157225/feefc65e-b23f-11e4-8851-325f9cd83689.png)

When using `static protected` it does:
![image](https://cloud.githubusercontent.com/assets/351038/6157243/15b5d91e-b240-11e4-9bd1-626575d628cd.png)

**Comment by infininight** [comment]
Corrected, thanks!

**Comment by koenpunt** [comment]
Cool, thanks!
