### ISSUE TITLE
dbl click variable name selection with $

### ISSUE THREAD

**Issue by broman-pl** [textmate/php.tmbundle#61]
is it possible to add $ when we double click on variable name to select it?

**Comment by infininight** [comment]
You want `$` selected as part of the word when you double click a variable? This is the default behavior in 2.0, so either you have a disabled bundle or have changed a setting.

Make sure you have the Source, Text, TextMate, Bundle Support, SCM, and Themes bundles all active in Preferences. Read the first two items in [this FAQ](https://github.com/textmate/textmate/wiki/FAQ) for information on how to do the reverse of what you want to make sure you haven't done that for another reason.

**Comment by broman-pl** [comment]
I didn't have "Source" bundle activated, Thanks
