### ISSUE TITLE
Cannot checkout master branch

### ISSUE THREAD

**Issue by jagomf** [textmate/php.tmbundle#67]
error: unable to create file Snippets/<?php $this->… ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php ?>.tmSnippet (Invalid argument)

error: unable to create file Snippets/<?php echo $this->… ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php echo ___ ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php echo htmlentities(___) ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php else: ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php foreach (___) ___ <?php endforeach ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/<?php if (___) ?> ___ <?php else ?> ___ <?php endif ?>.tmSnippet (Invalid argument)

error: unable to create file Snippets/<?php if (___) ?> ___ <?php endif ?>.tmSnippet (Invalid argument)
error: unable to create file Snippets/?>…<?php.tmSnippet (Invalid argument)

error: unable to create file Snippets/if ?: a : b;.tmSnippet (Invalid argument)

fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by sorbits** [comment]
Is this a request for help? If so, more info is needed, for example how 
you are trying to clone the repository and the version of the software 
involved.
