### ISSUE TITLE
Invalid syntax hilite

### ISSUE THREAD

**Issue by k-gun** [textmate/php.tmbundle#72]
Hi,

After PHP 7 updates for type-hints, function/method arguments can take default value more by its type. But GitHub (and Sublime GitHub theme) shows/assumes it as invalid syntax and is coloring by this way.

E.g:  

``` php
// this is valid, ok
function foo($x = 'Kerem')

// this is valid too, but colored as invalid
function foo(string $x = 'Kerem')
...
```

You can see these examples anytime in any [source](https://github.com/froq/froq-cache/blob/master/src/Agent/AgentInterface.php#L47) file.

Thank you!

**Comment by infininight** [comment]
This has been corrected by 706c68037661378f964657d00b85c3c8bdb8bec7, also added was return-type matching.

Note: Github pulls in grammar changes every 2-6 weeks, so it may be a bit before this is active on Github.
