### ISSUE TITLE
Failed to check php7 null coalescing operator (??)

### ISSUE THREAD

**Issue by andisulistyonugroho** [textmate/php.tmbundle#74]
I'm having this error while validating the PHP7 null coalescing operator

```
Parse error: parse error on line xxx
Errors parsing -
```

this is the code that I'm talking about
```
$buyerCompanyParameter = [
    "search" => "",
    "compGroup" => $comp->id ?? ""
];
```

**Comment by sorbits** [comment]
You did not include the first line of the output, which shows the 
version of PHP used to validate the syntax.

My guess would be that you are not using PHP 7 to validate the document.

**Comment by andisulistyonugroho** [comment]
Hi @sorbits you are correct, 
I changed the command using the one suggested in here http://powdahound.com/2008/05/textmate-tip-validate-your-php-syntax-when-saving/
and it did not show the version of PHP to validate it.

I put the old one back and it said I'm using php 5.5, I have php5 and php7 installed in OSX ElCapitan, can you give me suggestion on how to make the validator use php7?

**Comment by andisulistyonugroho** [comment]
hi @sorbits I found the solution by adding new variables on textmate preference and point it to my php7 `TM_PHP /usr/local/bin/php`

thanks for your help

**Comment by brucemagnani** [comment]
Hi, you have to point TM_PHP to your php installation dir.
I´ve made it before and just checked today.
TM_PHP /usr/local/"your php7 folder"/bin/php
Good luck
