### ISSUE TITLE
Injections key may not be valid

### ISSUE THREAD

**Issue by lildude** [textmate/php.tmbundle#77]
Ever since the injections key was changed:

```diff
<string>(\*/|^\s*\}|^HTML;)</string>
  <key>injections</key>
  <dict>
-   <key>text.html.php - (meta.embedded | meta.tag), L:text.html.php meta.tag, L:source.js.embedded.html</key>
+   <key>^text.html - (meta.embedded | meta.tag), L:^text.html meta.tag, L:source.js.embedded.html</key>
    <dict>
      <key>patterns</key>
      <array>
```

... in https://github.com/textmate/php.tmbundle/commit/9cfcc6d3c0fb76ef37232e28a4380f698f46ebcd we've not been able to update the PHP grammar in Linguist and thus used on GitHub.com and have had to keep using an old version, though we often forget, as I did earlier this week 😊 (https://github.com/github/linguist/issues/3601).

You can see this is in action in our Lightshow app:

- [Broken (current master)](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fphp.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FPHP.plist&grammar_text=&code_source=from-text&code_url=&code=%3C%3Fphp%0D%0A%24foo+%3D+123%3B%0D%0A%24bar+%3D+function%28%24foo%29+%7B%0D%0A++return+%24foo.%24foo.%281%2B2%29%3B%0D%0A%7D%0D%0A%24baz+%3D+array%28%27one%27%29%3B%0D%0A%24baz%5B%27two%27%5D+%3D+FALSE%3B%0D%0A%3F%3E)
- [Working (prior to 9cfcc6d)](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Fphp.tmbundle%2Fblob%2F3ed4837b43d3f650ebb525b068636281942883a0%2FSyntaxes%2FPHP.plist&grammar_text=&code_source=from-text&code_url=&code=%3C%3Fphp%0D%0A%24foo+%3D+123%3B%0D%0A%24bar+%3D+function%28%24foo%29+%7B%0D%0A++return+%24foo.%24foo.%281%2B2%29%3B%0D%0A%7D%0D%0A%24baz+%3D+array%28%27one%27%29%3B%0D%0A%24baz%5B%27two%27%5D+%3D+FALSE%3B%0D%0A%3F%3E)

Is this new injection key really valid?   
If so, can you reference other examples and/or implementation details on how this is parsed.

I can't find any documentation to suggest this is valid nor any other grammars using this "loose" scope. The highlighting in the Textmate Language Grammar editor suggests it may not be valid either:

New key:

<img width="901" alt="screen shot 2017-05-07 at 12 15 53" src="https://cloud.githubusercontent.com/assets/627280/25780389/25dbadde-331f-11e7-975d-9f39e5b80c1f.png">

Versus the old key:

<img width="899" alt="screen shot 2017-05-07 at 12 16 18" src="https://cloud.githubusercontent.com/assets/627280/25780392/2e640ff0-331f-11e7-9ed2-655d0058719d.png">

All other syntaxes show highlighting like this last image.

**Comment by infininight** [comment]
So I suspect the issue is the ^ character, though it's used in the previous one in a lesser manner. We added this in 2012 in TextMate to mean the start of the scope, I suspect this hasn't been added to the Github parser? If this is the case I can likely workaround the issue to get it working again.

**Comment by lildude** [comment]
> I suspect this hasn't been added to the Github parser?

I think this may be the case as it's definitely the `^` character causing problems.  I'll need to dig into the GitHub parser side of things.

Do you have a PR or issue I can reference in TextMate that introduced the support for the `^` (and possibly other) characters in the scope?

**Comment by infininight** [comment]
Believe this is all of the relevant commits:

https://github.com/textmate/textmate/compare/2ac005815b072f0577b21e44a7b5f45ba3bcfb7f...b21fbd897e095bf9378d79d9a54586c28da51b48

**Comment by lildude** [comment]
We've worked it out. This is indeed a problem with the GitHub parser. We had the functionality there already, we just had an off-by-one error 😂. A fix is coming to GitHub :soon:.

Closing this out.  Thanks for the info @infininight 🙇
