### ISSUE TITLE
Code inside <?php has blue background in Amiga theme

### ISSUE THREAD

**Issue by tcj** [textmate/php.tmbundle#79]
Hi -- I'm unsure why in TextMate 2.0, even the simplest of a PHP script file will change to a blue background for the PHP portion.  I am using the MagicWB/Amiga theme.

![screen shot 2017-07-14 at 1 51 21 pm](https://user-images.githubusercontent.com/2293335/28230486-154947da-689c-11e7-8d0c-e8f39bfee06e.png)

I was using pre-2.0 TextMate last night and this morning, and this blue background did not appear.

What can I do to get the standard gray background behind my php code?  Thanks.

**Comment by infininight** [comment]
Shouldn't be any reason for it to change but there is a reason for the blue color. The PHP code is a source scope embedded inside a text document. Many themes treat this as embedded code and provide a different background color to highlight the boundaries of the embedded code. You can switch themes to one that doesn't do this or edit the theme to disable that rule.
