### ISSUE TITLE
Highlighting doesn't work

### ISSUE THREAD

**Issue by konrad-bak** [textmate/php.tmbundle#83]
highlithing doesn't work, 02.10.2018, this is so sad, alexa play despacito.

i cloned repo, showed the directory in Settings > TextMate Bundles.
I read it correctly, showing "PHP" near the directory in the window, but nothing happaned. WebStorm restart doesn't give any effect, *.php are still plain text.

**Comment by sorbits** [comment]
We have no affiliation with WebStorm.

**Comment by konrad-bak** [comment]
;_;
